name: Bug Report
description: Report a bug to help us improve DuckX-PLusPlus
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please search existing issues before creating a new one to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a document with '...'
        2. Call method '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Actual behavior...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: cpp
      placeholder: |
        #include <duckx.hpp>
        
        int main() {
            // Your minimal reproduction code here
        }

  - type: dropdown
    id: api-type
    attributes:
      label: API Type
      description: Which API are you using?
      options:
        - Exception API (traditional)
        - Result<T> API (modern)
        - Both
        - Not sure
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: DuckX-PLusPlus Version
      description: Which version of DuckX-PLusPlus are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10/11
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - Linux (Other)
        - macOS
        - Other
    validations:
      required: true

  - type: dropdown
    id: compiler
    attributes:
      label: Compiler
      description: What compiler are you using?
      options:
        - Visual Studio 2019
        - Visual Studio 2022
        - GCC 9
        - GCC 10
        - GCC 11
        - GCC 12+
        - Clang 10
        - Clang 11
        - Clang 12+
        - Other
    validations:
      required: true

  - type: textarea
    id: build-info
    attributes:
      label: Build Configuration
      description: CMake options and build configuration
      placeholder: |
        cmake -DBUILD_SAMPLES=ON -DBUILD_TESTING=ON ..
        cmake --build . --config Release

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, provide the full error message or stack trace
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided a minimal code sample that reproduces the issue
          required: true
        - label: I am using a supported compiler and C++14 or later
          required: true