name: Feature Request
description: Suggest a new feature or enhancement for DuckX-PLusPlus
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        Please search existing issues and our [roadmap](../docs/ROADMAP.md) before creating a new request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Brief summary of the requested feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        I'm trying to accomplish... but currently I have to...
        This would be useful because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        I would like to be able to...
        The API could look like...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design Suggestion
      description: If applicable, suggest how the API should look
      render: cpp
      placeholder: |
        // Example API design
        auto result = document.new_feature_safe(parameters);
        if (result.ok()) {
            // Use the feature
        }

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Blocking my use case
        - Critical - Essential for adoption
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Document Reading/Writing
        - Table Formatting
        - Text Processing
        - Image/Media Handling
        - Error Handling
        - Performance
        - API Design
        - Build System
        - Documentation
        - Testing
        - Engineering Tools
        - Templates
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
        Why these don't work as well: ...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      render: cpp
      placeholder: |
        // Example 1: Basic usage
        auto doc = Document::create_safe("test.docx");
        auto result = doc.value().new_feature_safe();
        
        // Example 2: Advanced usage
        auto advanced_result = doc.value()
            .new_feature_safe()
            .and_then([](auto& result) {
                return result.configure_advanced_options();
            });

  - type: textarea
    id: compatibility
    attributes:
      label: Backward Compatibility
      description: How should this feature interact with existing APIs?
      placeholder: |
        - Should maintain compatibility with...
        - Might need to deprecate...
        - Could extend existing...

  - type: dropdown
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Would you be willing to help implement this feature?
      options:
        - Yes, I can implement it myself
        - Yes, I can help with guidance
        - Maybe, if someone guides me
        - No, I don't have the time/expertise
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, links, or references that would be helpful
      placeholder: |
        - Related to Microsoft Word feature: ...
        - Similar to library X: ...
        - Referenced in documentation: ...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and the roadmap for similar requests
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
        - label: I have provided clear use cases and examples
          required: true